# Generated by Django 4.2 on 2025-05-18 06:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_resenias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resenias',
            new_name='Resenia',
        ),
    ]
