# Generated by Django 4.2 on 2025-05-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(default='Ingrese la descripcion'),
            preserve_default=False,
        ),
    ]
