# Generated by Django 4.2 on 2025-05-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscar', '0002_libro_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
