INSERT INTO buscar_libro (titulo, autor, anio, genero) VALUES
('Lejos de la multitud', 'Thomas Hardy', 1874, 'Novela'),
('La montaña mágica', 'Thomas Mann', 1924, 'Novela'),
('Moby Dick', 'Herman Melville', 1851, 'Novela'),
('Ensayos', 'Michel de Montaigne', 1580, 'Ensayo'),
('La historia', 'Elsa Morante', 1974, 'Novela'),
('Beloved', 'Toni Morrison', 1987, 'Novela'),
('Genji Monogatari', 'Murasaki Shikibu', 0, 'Novela'),  -- Años aproximados (Siglo XI)
('El hombre sin atributos', 'Robert Musil', 1930, 'Novela'),
('Lolita', 'Vladimir Nabokov', 1955, 'Novela'),
('1984', 'George Orwell', 1949, 'Novela'),
('Las metamorfosis', 'Ovidio', 0, 'Poesía'),  -- Año aproximado (Siglo I d.C.)
('Libro del desasosiego', 'Fernando Pessoa', 1928, 'Prosa poética'),
('Cuentos', 'Edgar Allan Poe', 1845, 'Relatos'),
('En busca del tiempo perdido', 'Marcel Proust', 1913, 'Novela'),
('Gargantúa y Pantagruel', 'François Rabelais', 1532, 'Novela'),
('Pedro Páramo', 'Juan Rulfo', 1955, 'Novela'),
('Mathnawi', 'Jalal al-Din Rumi', 1258, 'Poesía'),  -- Año aproximado (Siglo XIII)
('Hijos de la medianoche', 'Salman Rushdie', 1981, 'Novela'),
('Bostan', 'Saadi', 1257, 'Poesía'),  -- Año aproximado (Siglo XIII)
('Tiempo de migrar al norte', 'Tayeb Salih', 1966, 'Novela'),
('Ensayo sobre la ceguera', 'José Saramago', 1995, 'Novela'),
('Hamlet', 'William Shakespeare', 1603, 'Drama'),
('El rey Lear', 'William Shakespeare', 1608, 'Drama'),
('Otelo', 'William Shakespeare', 1609, 'Drama'),
('Edipo rey', 'Sófocles', -500, 'Drama'),  -- Aprox. Siglo V a.C.
('Rojo y negro', 'Stendhal', 1830, 'Novela'),
('Vida y opiniones del caballero Tristram Shandy', 'Laurence Sterne', 1759, 'Novela'),
('La conciencia de Zeno', 'Italo Svevo', 1923, 'Novela'),
('Los viajes de Gulliver', 'Jonathan Swift', 1726, 'Novela'),
('Guerra y paz', 'León Tolstói', 1865, 'Novela'),
('Ana Karenina', 'León Tolstói', 1877, 'Novela'),
('La muerte de Iván Ilich', 'León Tolstói', 1886, 'Novela'),
('Las aventuras de Huckleberry Finn', 'Mark Twain', 1884, 'Novela'),
('Ramayana', 'Valmiki', -3000, 'Épica'),  -- Aprox. Siglo III–II a.C.
('Ulises', 'James Joyce', 1922, 'Novela'),
('Retrato del artista adolescente', 'James Joyce', 1916, 'Novela'),
('El gran Gatsby', 'F. Scott Fitzgerald', 1925, 'Novela'),
('Trampa 22', 'Joseph Heller', 1961, 'Novela'),
('El cero y el infinito', 'Arthur Koestler', 1940, 'Novela'),
('Hijos y amantes', 'D. H. Lawrence', 1913, 'Novela'),
('Las uvas de la ira', 'John Steinbeck', 1939, 'Novela'),
('La metamorfosis', 'Franz Kafka', 1915, 'Novela corta'),
('El proceso', 'Franz Kafka', 1925, 'Novela'),
('El castillo', 'Franz Kafka', 1926, 'Novela'),
('Shakuntala', 'Kalidasa', -400, 'Drama'),  -- Aprox. Siglo IV a.C.
('Zorba, el griego', 'Nikos Kazantzakis', 1946, 'Novela'),
('El ruido y la furia', 'William Faulkner', 1929, 'Novela'),
('¡Absalom, Absalom!', 'William Faulkner', 1936, 'Novela'),
('Madame Bovary', 'Gustave Flaubert', 1857, 'Novela'),
('La educación sentimental', 'Gustave Flaubert', 1869, 'Novela'),
('Romancero gitano', 'Federico García Lorca', 1928, 'Poesía'),
('Cien años de soledad', 'Gabriel García Márquez', 1967, 'Novela'),
('El amor en los tiempos del cólera', 'Gabriel García Márquez', 1985, 'Novela'),
('Fausto', 'Johann Wolfgang von Goethe', 1832, 'Drama'),
('Almas muertas', 'Nikolai Gogol', 1842, 'Novela'),
('El tambor de hojalata', 'Günter Grass', 1959, 'Novela'),
('Gran Sertón: Veredas', 'João Guimarães Rosa', 1956, 'Novela'),
('Hambre', 'Knut Hamsun', 1890, 'Novela'),
('El viejo y el mar', 'Ernest Hemingway', 1952, 'Novela'),
('Ilíada', 'Homero', -800, 'Épica'),  -- Aprox. Siglo VIII–VII a.C.
('Odisea', 'Homero', -800, 'Épica'),
('Casa de muñecas', 'Henrik Ibsen', 1879, 'Drama'),
('Relatos cortos', 'Franz Kafka', 1924, 'Relatos'),
('La divina comedia', 'Dante Alighieri', 1321, 'Poesía épica'),
('Orgullo y prejuicio', 'Jane Austen', 1813, 'Novela'),
('Papá Goriot', 'Honoré de Balzac', 1835, 'Novela');