INSERT INTO core_libro (id, titulo, autor, anio, genero, descripcion) VALUES
(1, 'Lejos de la multitud', 'Thomas Hardy', 1874, 'Novela', 'Ingrese la descripcion'),
(2, 'La montaña mágica', 'Thomas Mann', 1924, 'Novela', 'Ingrese la descripcion'),
(3, 'Moby Dick', 'Herman Melville', 1851, 'Novela', 'Ingrese la descripcion'),
(4, 'Ensayos', 'Michel de Montaigne', 1580, 'Ensayo', 'Ingrese la descripcion'),
(5, 'La historia', 'Elsa Morante', 1974, 'Novela', 'Ingrese la descripcion'),
(6, 'Beloved', 'Toni Morrison', 1987, 'Novela', 'Ingrese la descripcion'),
(7, 'Genji Monogatari', 'Murasaki Shikibu', 0, 'Novela', 'Ingrese la descripcion'),
(8, 'El hombre sin atributos', 'Robert Musil', 1930, 'Novela', 'Ingrese la descripcion'),
(9, 'Lolita', 'Vladimir Nabokov', 1955, 'Novela', 'Ingrese la descripcion'),
(10, '1984', 'George Orwell', 1949, 'Novela', 'Ingrese la descripcion'),
(11, 'Las metamorfosis', 'Ovidio', 0, 'Poesía', 'Ingrese la descripcion'),
(12, 'Libro del desasosiego', 'Fernando Pessoa', 1928, 'Prosa poética', 'Ingrese la descripcion'),
(13, 'Cuentos', 'Edgar Allan Poe', 1845, 'Relatos', 'Ingrese la descripcion'),
(14, 'En busca del tiempo perdido', 'Marcel Proust', 1913, 'Novela', 'Ingrese la descripcion'),
(15, 'Gargantúa y Pantagruel', 'François Rabelais', 1532, 'Novela', 'Ingrese la descripcion'),
(16, 'Pedro Páramo', 'Juan Rulfo', 1955, 'Novela', 'Ingrese la descripcion'),
(17, 'Mathnawi', 'Jalal al-Din Rumi', 1258, 'Poesía', 'Ingrese la descripcion'),
(18, 'Hijos de la medianoche', 'Salman Rushdie', 1981, 'Novela', 'Ingrese la descripcion'),
(19, 'Bostan', 'Saadi', 1257, 'Poesía', 'Ingrese la descripcion'),
(20, 'Tiempo de migrar al norte', 'Tayeb Salih', 1966, 'Novela', 'Ingrese la descripcion'),
(21, 'Ensayo sobre la ceguera', 'José Saramago', 1995, 'Novela', 'Ingrese la descripcion'),
(22, 'Hamlet', 'William Shakespeare', 1603, 'Drama', 'Ingrese la descripcion'),
(23, 'El rey Lear', 'William Shakespeare', 1608, 'Drama', 'Ingrese la descripcion'),
(24, 'Otelo', 'William Shakespeare', 1609, 'Drama', 'Ingrese la descripcion'),
(25, 'Edipo rey', 'Sófocles', -500, 'Drama', 'Ingrese la descripcion'),
(26, 'Rojo y negro', 'Stendhal', 1830, 'Novela', 'Ingrese la descripcion'),
(27, 'Vida y opiniones del caballero Tristram Shandy', 'Laurence Sterne', 1759, 'Novela', 'Ingrese la descripcion'),
(28, 'La conciencia de Zeno', 'Italo Svevo', 1923, 'Novela', 'Ingrese la descripcion'),
(29, 'Los viajes de Gulliver', 'Jonathan Swift', 1726, 'Novela', 'Ingrese la descripcion'),
(30, 'Guerra y paz', 'León Tolstói', 1865, 'Novela', 'Ingrese la descripcion'),
(31, 'Ana Karenina', 'León Tolstói', 1877, 'Novela', 'Ingrese la descripcion'),
(32, 'La muerte de Iván Ilich', 'León Tolstói', 1886, 'Novela', 'Ingrese la descripcion'),
(33, 'Las aventuras de Huckleberry Finn', 'Mark Twain', 1884, 'Novela', 'Ingrese la descripcion'),
(34, 'Ramayana', 'Valmiki', -3000, 'Épica', 'Ingrese la descripcion'),
(35, 'Ulises', 'James Joyce', 1922, 'Novela', 'Ingrese la descripcion'),
(36, 'Retrato del artista adolescente', 'James Joyce', 1916, 'Novela', 'Ingrese la descripcion'),
(37, 'El gran Gatsby', 'F. Scott Fitzgerald', 1925, 'Novela', 'Ingrese la descripcion'),
(38, 'Trampa 22', 'Joseph Heller', 1961, 'Novela', 'Ingrese la descripcion'),
(39, 'El cero y el infinito', 'Arthur Koestler', 1940, 'Novela', 'Ingrese la descripcion'),
(40, 'Hijos y amantes', 'D. H. Lawrence', 1913, 'Novela', 'Ingrese la descripcion'),
(41, 'Las uvas de la ira', 'John Steinbeck', 1939, 'Novela', 'Ingrese la descripcion'),
(42, 'La metamorfosis', 'Franz Kafka', 1915, 'Novela corta', 'Ingrese la descripcion'),
(43, 'El proceso', 'Franz Kafka', 1925, 'Novela', 'Ingrese la descripcion'),
(44, 'El castillo', 'Franz Kafka', 1926, 'Novela', 'Ingrese la descripcion'),
(45, 'Shakuntala', 'Kalidasa', -400, 'Drama', 'Ingrese la descripcion'),
(46, 'Zorba, el griego', 'Nikos Kazantzakis', 1946, 'Novela', 'Ingrese la descripcion'),
(47, 'El ruido y la furia', 'William Faulkner', 1929, 'Novela', 'Ingrese la descripcion'),
(48, '¡Absalom, Absalom!', 'William Faulkner', 1936, 'Novela', 'Ingrese la descripcion'),
(49, 'Madame Bovary', 'Gustave Flaubert', 1857, 'Novela', 'Ingrese la descripcion'),
(50, 'La educación sentimental', 'Gustave Flaubert', 1869, 'Novela', 'Ingrese la descripcion'),
(51, 'Romancero gitano', 'Federico García Lorca', 1928, 'Poesía', 'Ingrese la descripcion'),
(52, 'Cien años de soledad', 'Gabriel García Márquez', 1967, 'Novela', 'Ingrese la descripcion'),
(53, 'El amor en los tiempos del cólera', 'Gabriel García Márquez', 1985, 'Novela', 'Ingrese la descripcion'),
(54, 'Fausto', 'Johann Wolfgang von Goethe', 1832, 'Drama', 'Ingrese la descripcion'),
(55, 'Almas muertas', 'Nikolai Gogol', 1842, 'Novela', 'Ingrese la descripcion'),
(56, 'El tambor de hojalata', 'Günter Grass', 1959, 'Novela', 'Ingrese la descripcion'),
(57, 'Gran Sertón: Veredas', 'João Guimarães Rosa', 1956, 'Novela', 'Ingrese la descripcion'),
(58, 'Hambre', 'Knut Hamsun', 1890, 'Novela', 'Ingrese la descripcion'),
(59, 'El viejo y el mar', 'Ernest Hemingway', 1952, 'Novela', 'Ingrese la descripcion'),
(60, 'Ilíada', 'Homero', -800, 'Épica', 'Ingrese la descripcion'),
(61, 'Odisea', 'Homero', -800, 'Épica', 'Ingrese la descripcion'),
(62, 'Casa de muñecas', 'Henrik Ibsen', 1879, 'Drama', 'Ingrese la descripcion'),
(63, 'Relatos cortos', 'Franz Kafka', 1924, 'Relatos', 'Ingrese la descripcion'),
(64, 'La divina comedia', 'Dante Alighieri', 1321, 'Poesía épica', 'Ingrese la descripcion'),
(65, 'Orgullo y prejuicio', 'Jane Austen', 1813, 'Novela', 'Ingrese la descripcion'),
(66, 'Papá Goriot', 'Honoré de Balzac', 1835, 'Novela', 'Ingrese la descripcion');
